### ISSUE TITLE
Timeout not working as expected

### ISSUE THREAD

**Issue by oscard0m** [gr2m/await-npm-package-version-action#43]
When running a job and the registry is not being resolved properly, the timeout is not taking the desired effect to stop the execution.

---

I'm still getting a never ending GitHub Action execution: https://github.com/oscard0m/sandbox/runs/2504376343?check_suite_focus=true. Do you want me to create a follow up issue for this?

---

_Originally posted by @oscard0m in https://github.com/gr2m/await-npm-package-version-action/issues/39#issuecomment-832299905_

**Comment by gr2m** [comment]
do you want to investigate this a bit more yourself? I'm pretty swamped right now. I thought that `core.error` exists the process, but it looks it that's not the case here

**Comment by oscard0m** [comment]
> do you want to investigate this a bit more yourself? I'm pretty swamped right now. I thought that `core.error` exists the process, but it looks it that's not the case here

I take it 😃
