### ISSUE TITLE
Getting SyntaxError on runs: `SyntaxError: Unexpected token '?'`

### ISSUE THREAD

**Issue by wolfy1339** [gr2m/await-npm-package-version-action#85]
Workflow logs: https://github.com/octokit/webhooks/runs/4611647515?check_suite_focus=true

Last known working time was 29 days ago ([this workflow](https://github.com/octokit/webhooks/runs/4305355708?check_suite_focus=true)), which would have been using `v1.1.5`

**Comment by gr2m** [comment]
Need to downgrade `got` and tell dependabot to stop upgrading it. Can you send a PR? I gotta run right now

**Comment by wolfy1339** [comment]
Hey @gr2m it seems this issue has popped up again.
https://github.com/gr2m/await-npm-package-version-action/commit/5dc2ffa59e1844d4e527ecbd4e707aae52515922 reintroduced `got@v12`

**Comment by gr2m** [comment]
ugh sorry
